# Generated by Django 4.1 on 2023-11-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_customuser_workspace_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='workspace',
            field=models.CharField(max_length=200),
        ),
    ]
