# Generated by Django 4.1 on 2023-11-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_alter_customuser_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_superuser',
        ),
    ]
