# Generated by Django 4.1 on 2023-11-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
