# Generated by Django 4.1 on 2023-11-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_customuser_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
